version: '3'
services:
    db:
        image: postgres:9.4
        volumes:
            - /srv/tomo-dbdata/:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=tomo
            - POSTGRES_DB=tomo
            - POSTGRES_PASSWORD=tomo

    app:
        image: matijapretnar/projekt-tomo
        ports:
            - "8080:8080"
        links:
            - db
        environment:
            - DJANGO_SETTINGS_MODULE=web.settings.arnes
            - SECRET_KEY=TODO
            - SOCIAL_AUTH_GOOGLE_OAUTH2_KEY=TODO
            - SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET=TODO
            - SOCIAL_AUTH_FACEBOOK_KEY=TODO
            - SOCIAL_AUTH_FACEBOOK_SECRET=TODO
            - SOCIAL_AUTH_TWITTER_KEY=TODO
            - SOCIAL_AUTH_TWITTER_SECRET=TODO
            - UWSGI_CHDIR=/home/tomo/projekt-tomo/web
            - UWSGI_MODULE=web.wsgi.arnes:application
            - UWSGI_MASTER=True
            - UWSGI_PIDFILE=/tmp/project-master.pid
            - UWSGI_VACUUM=True
            - UWSGI_MAX_REQUESTS=5000
            - UWSGI_UID=tomo
            - UWSGI_GID=tomo
            - UWSGI_SOCKET=:8080
            - UWSGI_PLUGINS=python3
            - UWSGI_STATIC_MAP=/static=/home/tomo/projekt-tomo/web/static
