version: "3"
   
services:
  db:
    image: postgres:${POSTGRES_VERSION}
    restart: always
    volumes:
      - ${POSTGRES_DATA_PATH}:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
  web:
    build: web
    restart: always
    volumes:
      - ${STATIC_PATH}:/var/static
    ports:
      - "${HTTP_PORT}:8080"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE
      - ALLOWED_HOSTS
      - SECRET_KEY
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - SOCIAL_AUTH_GOOGLE_OAUTH2_KEY
      - SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET
      - SOCIAL_AUTH_FACEBOOK_KEY
      - SOCIAL_AUTH_FACEBOOK_SECRET