version: "3"
   
services:
  db:
    image: postgres:${POSTGRES_VERSION}
    restart: always
    volumes:
      - ${POSTGRES_DATA_PATH}:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
  web:
    build: web
    restart: always
    ports:
      - "${HTTP_PORT}:8080"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE
      - ALLOWED_HOSTS
      - SECRET_KEY
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - SOCIAL_AUTH_GOOGLE_OAUTH2_KEY
      - SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET
      - SOCIAL_AUTH_FACEBOOK_KEY
      - SOCIAL_AUTH_FACEBOOK_SECRET
      - STATIC_ROOT
      - STATIC_URL
      - UWSGI_CHDIR=/src
      - UWSGI_MODULE=web.wsgi.arnes:application
      - UWSGI_MASTER=True
      - UWSGI_PIDFILE=/tmp/project-master.pid
      - UWSGI_VACUUM=True
      - UWSGI_MAX_REQUESTS=5000
      - UWSGI_UID=tomo
      - UWSGI_GID=tomo
      - UWSGI_HTTP=:8080
      - UWSGI_PLUGINS=python3
      - UWSGI_STATIC_MAP=${STATIC_URL}=${STATIC_ROOT}
