name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - uses: jamescurtin/isort-action@master
        with:
          requirementsFiles: "web/requirements/common.txt"
